name: example
description: Atlas + Google Atlas example project
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 7.2.0
  equatable: 2.0.3
  rxdart: 0.26.0
  google_atlas:
    path: ../packages/google_atlas

flutter:
  uses-material-design: true
  assets:
    - assets/
