name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.5
  equatable: ^1.1.1
  google_atlas:
    path: ../packages/google_atlas

flutter:
  uses-material-design: true
  assets:
    - assets/
