name: atlas
description: An extensible map abstraction for Flutter with support for multiple map providers
version: 0.17.1
repository: https://github.com/bmw-tech/atlas
issue_tracker: https://github.com/bmw-tech/atlas/issues
homepage: https://bmw-tech.github.io/atlas

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.0.3

dependency_overrides:
  mockito: 5.0.3
  analyzer: 1.1.0
  test_api: 0.2.19
