name: atlas
description: An extensible map abstraction for Flutter with support for multiple map providers
version: 0.5.1
authors:
  - Jorge Coca <jcocaramos@gmail.com>
  - Felix Angelov <felangelov@gmail.com>
  - Noah Mateen <noahmateen@gmail.com>
  - Tim Chabot <tchabot22@gmail.com>
repository: https://github.com/bmw-tech/atlas
issue_tracker: https://github.com/bmw-tech/atlas/issues
homepage: https://bmw-tech.github.io/atlas

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
