name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_flutter_atlas:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["packages/atlas"]
        channel: ["stable"]

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          flags: atlas
          file: ./coverage/lcov.info

  build_flutter_google_atlas:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["packages/google_atlas"]
        channel: ["stable"]

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          flags: atlas
          file: ./coverage/lcov.info
