name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["packages/atlas", "packages/google_atlas"]
        channel: ["stable"]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to Codecov 
        if: success()
        run: |
          curl -s https://codecov.io/bash -o codecov.sh
          bash codecov.sh -F ${{ matrix.codecov-flag }}
        env:
          CODECOV_NAME: ${{ matrix.package }}