name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_flutter:
    runs-on: ubuntu-latest
    env:
      PACKAGE_PREFIX: "packages/"

    strategy:
      matrix:
        package: ["atlas", "google_atlas"]
        channel: ["stable"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ matrix.package }}/env.PACKAGE_PREFIX

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}/env.PACKAGE_PREFIX

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info
        working-directory: ${{ matrix.package }}/env.PACKAGE_PREFIX

      - name: Upload coverage to Codecov
        if: success()
        run: |
          bash <(curl -s https://codecov.io/bash) -c -F ${{ matrix.package }}
        env:
          CODECOV_NAME: ${{ matrix.package }}
