name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["packages/atlas", "packages/google_atlas"]
        channel: ["stable"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to Codecov
        if: success()
        run: |
          package_str=${{ matrix.package }}
          codecov_flag="${package_str//packages\/}"
          bash <(curl -s https://codecov.io/bash) -c -F $codecov_flag
        env:
          CODECOV_NAME: ${{ matrix.package }}
