name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["packages/atlas", "packages/google_atlas"]
        channel: ["stable"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: |
          package_str=${{ matrix.package }}
          codecov_flag="${package_str//packages\/}"
          echo "CODECOV_FLAG=${codecov_flag}" >> "$GITHUB_ENV"
          flutter packages get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: $CODECOV_FLAG
          file: ./${{ matrix.package }}/coverage/lcov.info
